export const SET_LOCATION = {
  REQ_LOCATION: "REQ_LOCATION",
  REQ_LOCATION_SUCCESS: "REQ_LOCATION_SUCCESS",
  REQ_LOCATION_FAIL: "REQ_LOCATION_FAIL",
};
export const SET_CONSOLIDATED_WEATHER = {
  REQ_CONSOLIDATED_WEATHER: "REQ_CONSOLIDATED_WEATHER",
  REQ_CONSOLIDATED_WEATHER_SUCCESS: "REQ_CONSOLIDATED_WEATHER_SUCCESS",
  REQ_CONSOLIDATED_WEATHER_FAIL: "REQ_CONSOLIDATED_WEATHER_FAIL",
};
